### ISSUE TITLE
Pre-release content issues for MackTrucks Helix5 Upgrade Market Sites

### ISSUE THREAD

**Issue by silviulungu** [aemsites/vg-macktrucks-com#40]
[Australia](https://main--macktrucks-com-au--volvogroup.aem.live/)

- [x] Sub-nav missing: https://main--macktrucks-com-au--volvogroup.aem.live/powertrain-and-suspensions/engines/
- [x] [In PROD] Engine mp11 redirects the user to mp10 https://main--macktrucks-com-au--volvogroup.aem.live/powertrain-and-suspensions/engines/mp10/
- [x] Sub-nav-container is missing https://main--macktrucks-com-au--volvogroup.aem.live/magazine/
- [x] Accordion container missing content on engines https://main--macktrucks-com-au--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
- [x] Accordion container missing content on transmissions https://main--macktrucks-com-au--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/ **(The accordion needs to be switched to the v2-accordion component and the page published)**

[Argentina](https://main--macktrucks-com-ar--volvogroup.aem.live/)

 - [x] [IN PROD] "null" word is present in download-spec-section: https://main--macktrucks-com-ar--volvogroup.aem.live/powertrain-and-suspensions/suspensions/mride/
 - [x] [IN PROD] Missing PDF: https://main--macktrucks-com-ar--volvogroup.aem.live/powertrain-and-suspensions/suspensions/mride/
 - [x] Accordion container missing content on engines https://main--macktrucks-com-ar--volvogroup.aem.live/powertrain-and-suspensions/engines/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
 - [x] Accordion container missing content on transmissions https://main--macktrucks-com-ar--volvogroup.aem.live/powertrain-and-suspensions/transmissions/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
 - [x] [IN PROD] Missing content https://main--macktrucks-com-ar--volvogroup.aem.live/request-a-quote/
 - [x] [IN PROD] Missing content https://main--macktrucks-com-ar--volvogroup.aem.live/trucks/events/
 - [x] [IN PROD] Truck builder redirects the user to this link https://build.macktrucks.com.mx/ 
 - [x] Missing content https://main--macktrucks-com-ar--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
 - [x] Missing content https://main--macktrucks-com-ar--volvogroup.aem.live/powertrain-and-suspensions/engines/scr/

[Bolivia](https://main--macktrucks-com-bo--volvogroup.aem.live/)

 - [x] Accordion container missing content on engines https://main--macktrucks-com-bo--volvogroup.aem.live/powertrain-and-suspensions/engines/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
 - [x] Accordion container missing content on transmissions https://main--macktrucks-com-bo--volvogroup.aem.live/powertrain-and-suspensions/transmissions/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
 - [x] [IN PROD] Missing content https://main--macktrucks-com-bo--volvogroup.aem.live/request-a-quote/
 - [x] [IN PROD] Missing content https://main--macktrucks-com-bo--volvogroup.aem.live/trucks/events/
 - [x] [IN PROD] Truck builder redirects the user to this link https://www.macktrucks.com/trucks/build/
  - [x] [IN PROD] Missing content https://main--macktrucks-com-bo--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
 - [x] Missing content https://main--macktrucks-com-bo--volvogroup.aem.live/powertrain-and-suspensions/engines/scr/
 - [x] Missing content  https://main--macktrucks-com-bo--volvogroup.aem.live/powertrain-and-suspensions/exhaust-aftertreatment-systems/

[Chile](https://main--macktrucks-cl--volvogroup.aem.live/)

 - [x] [IN PROD] Redirects the user to https://build.macktrucks.com.mx/
 - [x] Missing content https://main--macktrucks-cl--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
 - [x] Missing content https://main--macktrucks-cl--volvogroup.aem.live/powertrain-and-suspensions/engines/scr/
 - [x] [IN PROD] Missing content https://main--macktrucks-cl--volvogroup.aem.live/parts-and-services/parts/partsasist/
 - [x] [IN PROD] Missing content https://main--macktrucks-cl--volvogroup.aem.live/powertrain-and-suspensions/exhaust-aftertreatment-systems/
 - [x] [IN PROD] Missing content https://main--macktrucks-cl--volvogroup.aem.live/buy-mack/request-a-quote/
 - [x] Accordion container missing content on engines https://main--macktrucks-cl--volvogroup.aem.live/powertrain-and-suspensions/engines/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
 - [x] Accordion container missing content on transmissions https://main--macktrucks-cl--volvogroup.aem.live/powertrain-and-suspensions/transmissions/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
 
[Ecuador](https://main--macktrucks-com-ec--volvogroup.aem.live/)

 - [x] Accordion container missing content on transmissions https://main--macktrucks-com-ec--volvogroup.aem.live/powertrain-and-suspensions/transmissions/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
 - [x] Accordion container missing content on engines https://main--macktrucks-com-ec--volvogroup.aem.live/powertrain-and-suspensions/engines/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
 - [x] [IN PROD] Redirects the user to https://build.macktrucks.com.mx/
 - [x] [IN PROD] Missing content https://main--macktrucks-com-ec--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
 - [x] Missing content https://main--macktrucks-com-ec--volvogroup.aem.live/powertrain-and-suspensions/engines/scr/
 - [x] [IN PROD] Missing content https://main--macktrucks-com-ec--volvogroup.aem.live/powertrain-and-suspensions/exhaust-aftertreatment-systems/
 - [x] [IN PROD] Missing content https://main--macktrucks-com-ec--volvogroup.aem.live/parts-and-services/parts/partsasist/
 - [x] [IN PROD] Missing content https://main--macktrucks-com-ec--volvogroup.aem.live/buy-mack/request-a-quote/

[Guyana](https://main--macktrucks-com-gy--volvogroup.aem.live/)

 - [x] Accordion container missing content on transmissions https://main--macktrucks-com-gy--volvogroup.aem.live/powertrain-and-suspensions/transmissions/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
 - [x] Accordion container missing content on engines https://main--macktrucks-com-gy--volvogroup.aem.live/powertrain-and-suspensions/engines/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
 - [x] Redirects the user to https://www.macktrucks.com/trucks/md/build/#/md
 - [x] [IN PROD] Missing content https://main--macktrucks-com-gy--volvogroup.aem.live/powertrain-and-suspensions/suspensions/mrIde/

[Peru](https://main--macktrucks-com-pe--volvogroup.aem.live/)

 - [x] Missing content https://main--macktrucks-com-pe--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
 - [x] Missing content https://main--macktrucks-com-pe--volvogroup.aem.live/powertrain-and-suspensions/engines/scr/
 - [x] Missing content https://main--macktrucks-com-pe--volvogroup.aem.live/powertrain-and-suspensions/exhaust-aftertreatment-systems/
 - [x] Redirects the user to this https://build.macktrucks.com.mx/
 - [x] Missing content https://main--macktrucks-com-pe--volvogroup.aem.live/parts-and-services/parts/partsasist/
 - [x] [IN PROD] Missing content https://main--macktrucks-com-pe--volvogroup.aem.live/buy-mack/request-a-quote/
 - [x] Missing subscribe form https://main--macktrucks-com-pe--volvogroup.aem.live/magazine/

[Venezuela](https://main--macktrucks-com-ve--volvogroup.aem.live/)

 - [x] Redirects the user to https://build.macktrucks.com.mx/
 - [x] Missing content https://main--macktrucks-com-ve--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
 - [x] Missing content https://main--macktrucks-com-ve--volvogroup.aem.live/powertrain-and-suspensions/exhaust-aftertreatment-systems/
 - [x] Missing content https://main--macktrucks-com-ve--volvogroup.aem.live/parts-and-services/parts/partsasist/
 - [x] [IN PROD] Missing content https://main--macktrucks-com-ve--volvogroup.aem.live/buy-mack/request-a-quote/

[Dominican Republic](https://main--macktrucks-com-do--volvogroup.aem.live/)

 - [x] Redirects the user to this https://build.macktrucks.com.mx/
 - [x] Missing content https://main--macktrucks-com-do--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
 - [x] [IN PROD] Missing content https://main--macktrucks-com-do--volvogroup.aem.live/powertrain-and-suspensions/exhaust-aftertreatment-systems/
 - [x] [IN PROD] Missing content https://main--macktrucks-com-do--volvogroup.aem.live/buy-mack/request-a-quote/
 - [x] [IN PROD] Missing content https://main--macktrucks-com-do--volvogroup.aem.live/trucks/events/

[Haiti](https://main--macktrucks-ht--volvogroup.aem.live/)

 - [x] [IN PROD] Missing content https://main--macktrucks-ht--volvogroup.aem.live/trucks/events/
 - [x] ? Redirects the user to https://www.macktrucks.com/trucks/md/build/#/md

[Costa Rica](https://main--macktrucks-cr--volvogroup.aem.live/)

 - [x] Redirects the user to https://build.macktrucks.com.mx/
 - [x] Missing content https://main--macktrucks-cr--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
 - [x] Missing content https://main--macktrucks-cr--volvogroup.aem.live/powertrain-and-suspensions/exhaust-aftertreatment-systems/
 - [x] Missing content https://main--macktrucks-cr--volvogroup.aem.live/parts-and-services/parts/partsasist/
 - [x] [IN PROD] Missing content https://main--macktrucks-cr--volvogroup.aem.live/buy-mack/request-a-quote/
 - [x] [IN PROD] Missing content https://main--macktrucks-cr--volvogroup.aem.live/trucks/events/

[Guatemala](https://main--macktrucks-gt--volvogroup.aem.live/)

- [x] [IN PROD] Page broken - https://main--macktrucks-gt--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
- [x] Accordion broken - https://main--macktrucks-gt--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
- [x] Accordion broken - https://main--macktrucks-gt--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/ **(The accordion needs to be switched to the v2-accordion component and the page published)**
- [x] [IN PROD] Page missing - https://main--macktrucks-gt--volvogroup.aem.live/powertrain-and-suspensions/exhaust-aftertreatment-systems/
- [x] [IN PROD] Page missing - https://main--macktrucks-gt--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8he/
- [x] [IN PROD] Page missing - https://main--macktrucks-gt--volvogroup.aem.live/mack-connect/

[Honduras](https://main--macktrucks-hn--volvogroup.aem.live/)
**(The accordion needs to be switched to the v2-accordion component and the page published)**
- [x] Accordion is broken - https://main--macktrucks-hn--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] Accordion is broken - https://main--macktrucks-hn--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
- [x] Accordion is broken - https://main--macktrucks-hn--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] Accordion is broken - https://main--macktrucks-hn--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] [IN PROD] Missing page - https://main--macktrucks-hn--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8he/
- [x] [IN PROD] Missing page - https://main--macktrucks-hn--volvogroup.aem.live/mack-connect/
- [x] [IN PROD] Configurator broken - https://build.macktrucks.com.mx/

[**Panama**](https://main--macktrucks-com-pa--volvogroup.aem.live/)

- [x] [IN PROD] Missing page: https://main--macktrucks-com-pa--volvogroup.aem.live/buy-mack/find-a-dealer/
- [x] [IN PROD] Builder redirects the user to this: https://build.macktrucks.com.mx/
- [x] [IN PROD] Missing PDFs: https://main--macktrucks-com-pa--volvogroup.aem.live/trucks/anthem/specs/
- [x] [IN PROD] Missing PDFs: https://main--macktrucks-com-pa--volvogroup.aem.live/trucks/granite-series/specs/
- [x] [IN PROD] Missing page: https://main--macktrucks-com-pa--volvogroup.aem.live/parts-and-services/support/body-builders/wiring-diagrams/
- [x] [IN PROD] Missing PDFs: https://main--macktrucks-com-pa--volvogroup.aem.live/parts-and-services/support/body-builders/
- [x] [IN PROD] Missing page: https://main--macktrucks-com-pa--volvogroup.aem.live/buy-mack/request-a-quote/
- [x] [IN PROD] Missing page: https://main--macktrucks-com-pa--volvogroup.aem.live/trucks/events/
- [x] [IN PROD] Missing page: https://main--macktrucks-com-pa--volvogroup.aem.live/about-mack/facilities/mack-lehigh-valley-operations/
- [x] [IN PROD] Sub-nav does not respect the site language, some words are in English.
- [x] [IN PROD] Missing PDF- https://main--macktrucks-com-pa--volvogroup.aem.live/parts-and-services/parts/remack/
- [x] [IN PROD] Tabs block options do not work - https://main--macktrucks-com-pa--volvogroup.aem.live/parts-and-services/parts/remack/engine/
- [x] [IN PROD] Missing PDF - https://main--macktrucks-com-pa--volvogroup.aem.live/powertrain-and-suspensions/suspensions/mride/
- [x] [IN PROD] Missing PDF - https://main--macktrucks-com-pa--volvogroup.aem.live/powertrain-and-suspensions/suspensions/liftable-axle/
- [x] [IN PROD] Missing PDF - https://main--macktrucks-com-pa--volvogroup.aem.live/powertrain-and-suspensions/axles/features/
- [x] [IN PROD] Missing PDFs - https://main--macktrucks-com-pa--volvogroup.aem.live/powertrain-and-suspensions/axles/axles-carriers/
- [x] [IN PROD] Missing PDFs - https://main--macktrucks-com-pa--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] [IN PROD] Missing PDFs - https://main--macktrucks-com-pa--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] [IN PROD] Missing page - https://main--macktrucks-com-pa--volvogroup.aem.live/NASCAR

[**Nicaragua**](https://main--macktrucks-com-ni--volvogroup.aem.live/) 

- [x] [IN PROD] PDFs missing - https://main--macktrucks-com-ni--volvogroup.aem.live/magazine/bulldog-magazine
- [x] [IN PROD] Page missing - https://main--macktrucks-com-ni--volvogroup.aem.live/trucks/events/
- [x] [IN PROD] Page missing - https://main--macktrucks-com-ni--volvogroup.aem.live/about-mack/facilities/mack-lehigh-valley-operations/
- [x] [IN PROD] Page missing - https://main--macktrucks-com-ni--volvogroup.aem.live/mack-connect/connected-driving/
- [x] Accordion broken - https://main--macktrucks-com-ni--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] Accordion broken - https://main--macktrucks-com-ni--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] Accordion broken - https://main--macktrucks-com-ni--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] [IN PROD] Video does not work - https://main--macktrucks-com-ni--volvogroup.aem.live/powertrain-and-suspensions/axles/axles-carriers/
- [x] [IN PROD] Page missing - https://main--macktrucks-com-ni--volvogroup.aem.live/powertrain-and-suspensions/suspensions/mrIde/
- [x] [IN PROD] PDFs missing - https://main--macktrucks-com-ni--volvogroup.aem.live/powertrain-and-suspensions/suspensions/liftable-axle/
- [x] [IN PROD] Videos broken - https://main--macktrucks-com-ni--volvogroup.aem.live/trucks/anthem/
- [x] [IN PROD] Page missing - https://main--macktrucks-com-ni--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8he

[EMEA](https://main--macktrucks-com-emea--volvogroup.aem.live/)
**(The accordion needs to be switched to the v2-accordion component and the page published)**
- [x] [IN PROD] Request a quote page - https://main--macktrucks-com-emea--volvogroup.aem.live/buy-mack/request-a-quote/
- [x] [IN PROD] Page missing - https://main--macktrucks-com-emea--volvogroup.aem.live/mack-connect/connected-driving/
- [x] [IN PROD] Video broken - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] Accordion are broken - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] [IN PROD] Page missing - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
- [x] [IN PROD] Video broken - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] Accordion broken - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] Accordion broken - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] [IN PROD] The heavy-duty heavyweight section is broken - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/axles/features/
- [x] Accordion broken - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/axles/features/
- [x] [IN PROD] Videos broken  - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/axles/axles-carriers/
- [x] Accordion broken - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/axles/axles-carriers/
- [x] Accordion broken - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/suspensions/mride/
- [x] [IN PROD] Page missing - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/suspensions/mrIde/
- [x] [IN PROD] Videos broken - https://main--macktrucks-com-emea--volvogroup.aem.live/trucks/anthem/
- [x] [IN PROD] Page missing - https://main--macktrucks-com-emea--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8he

[Trinidad & Tobago](https://main--macktrucks-tt--volvogroup.aem.live/)
**(The accordion needs to be switched to the v2-accordion component and the page published)**
- [x] [IN PROD] Request a quote page missing - https://main--macktrucks-tt--volvogroup.aem.live/buy-mack/request-a-quote/
- [x] [IN PROD] Page missing - https://main--macktrucks-tt--volvogroup.aem.live/mack-connect/connected-driving/
- [x] [IN PROD] Page missing - https://main--macktrucks-tt--volvogroup.aem.live/parts-and-services/uptime-solutions/diagnostic-tools/
- [x] Accordion broken - https://main--macktrucks-tt--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] [IN PROD] Page missing - https://main--macktrucks-tt--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
- [x] [IN PROD] Video not working - https://main--macktrucks-tt--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] Accordion broken - https://main--macktrucks-tt--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] Accordion broken -https://main--macktrucks-tt--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] [IN PROD] “Read more” button offset - https://main--macktrucks-tt--volvogroup.aem.live/powertrain-and-suspensions/axles/
- [x] Accordion broken - https://main--macktrucks-tt--volvogroup.aem.live/powertrain-and-suspensions/axles/features/
- [x] Accordion broken - https://main--macktrucks-tt--volvogroup.aem.live/powertrain-and-suspensions/axles/axles-carriers/
- [x] [IN PROD] Typo on “Rediscover” + videos do not work on this page - https://main--macktrucks-tt--volvogroup.aem.live/trucks/anthem/
- [x] [IN PROD] Page missing - https://main--macktrucks-tt--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8he

[Bahamas](https://main--macktrucks-bs--volvogroup.aem.live/)

- [x] [IN PROD] Request a quote page missing - https://main--macktrucks-bs--volvogroup.aem.live/buy-mack/request-a-quote/
- [x] [IN PROD] Description button written in spanish - https://main--macktrucks-bs--volvogroup.aem.live/about-mack/
- [x] [IN PROD] Page missing - https://main--macktrucks-bs--volvogroup.aem.live/mack-connect/connected-driving/
- [x] Accordion broken - https://main--macktrucks-bs--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] Videos don't not work - https://main--macktrucks-bs--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] Accordion broken - https://main--macktrucks-bs--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] Accordion broken - https://main--macktrucks-bs--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] Video does not work - https://main--macktrucks-bs--volvogroup.aem.live/powertrain-and-suspensions/axles/features/
- [x] Accordion broken - https://main--macktrucks-bs--volvogroup.aem.live/powertrain-and-suspensions/axles/features/
- [x] Videos does not work - https://main--macktrucks-bs--volvogroup.aem.live/powertrain-and-suspensions/axles/axles-carriers/
- [x] Accordion broken - https://main--macktrucks-bs--volvogroup.aem.live/powertrain-and-suspensions/axles/axles-carriers/
- [x] [IN PROD] Typo on “Rediscover” - https://main--macktrucks-bs--volvogroup.aem.live/trucks/anthem/
- [x] Videos do not work - https://main--macktrucks-bs--volvogroup.aem.live/trucks/anthem/
- [x] [IN PROD] Page missing - https://main--macktrucks-bs--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8he

[El Salvador](https://main--macktrucks-sv--volvogroup.aem.live/)

- [x] [IN PROD] Request a quote page missing - https://main--macktrucks-sv--volvogroup.aem.live/buy-mack/request-a-quote/
- [x] [IN PROD] Page missing - https://main--macktrucks-sv--volvogroup.aem.live/powertrain-and-suspensions/exhaust-aftertreatment-systems/
- [x] Accordion is broken - https://main--macktrucks-sv--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] Page missing - https://main--macktrucks-sv--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
- [x] Accordion is broken - https://main--macktrucks-sv--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] Accordion is broken - https://main--macktrucks-sv--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] [IN PROD] Page missing - https://main--macktrucks-sv--volvogroup.aem.live/mack-connect/
- [x] [IN PROD] Page missing - https://main--macktrucks-sv--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8he/
- [x] [IN PROD] Configurator missing - https://build.macktrucks.com.mx/
- [x] Subscribe button missing - https://main--macktrucks-sv--volvogroup.aem.live/magazine/

[Nigeria](https://main--macktrucks-com-ng--volvogroup.aem.live/)

- [x] [IN PROD] Request a quote page missing - https://main--macktrucks-com-ng--volvogroup.aem.live/buy-mack/request-a-quote/
- [x] [IN PROD] Connected drive page missing - https://main--macktrucks-com-ng--volvogroup.aem.live/mack-connect/connected-driving/
- [x] [IN PROD] Service and Maintenance intervals options are giving 404 on both Helix Live and AEM Live - https://main--macktrucks-com-ng--volvogroup.aem.live/parts-and-services/support/  /    https://www.macktrucksnigeria.com/parts-and-services/support/
- [x] Accordion broken - https://main--macktrucks-com-ng--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] [IN PROD] MP7 page missing - https://main--macktrucks-com-ng--volvogroup.aem.live/powertrain-and-suspensions/engines/mp7/
- [x] Accordion broken - https://main--macktrucks-com-ng--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] Accordion  broken - https://main--macktrucks-com-ng--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] 2 out of 3 videos do not start - https://main--macktrucks-com-ng--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] “Read more” on Axle Carriers menu is not center - https://main--macktrucks-com-ng--volvogroup.aem.live/powertrain-and-suspensions/axles/
- [x] [IN PROD] Videos broken on this page - https://main--macktrucks-com-ng--volvogroup.aem.live/trucks/anthem/
- [x] [IN PROD] Page missing - https://main--macktrucks-com-ng--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8he

[Museum](https://main--macktrucks-com-museum--volvogroup.aem.live/)

- [x] [IN PROD] NM 1945 Mack 6-Ton video not available - https://www.macktruckshistoricalmuseum.org/videos/
- [x] [IN PROD] 1940 Mack ED video missing - https://www.macktruckshistoricalmuseum.org/videos/
- [x] [IN PROD] Social block have only two links (Facebook and Youtube), this is the right behavior?

**Comment by Kannan-CM** [comment]
Issues mentioned on this ticket have been addressed

**Comment by silviulungu** [comment]
Testing completed, here are the observations:

**Missing content:**

Bolivia 
https://www.macktrucks.com.bo/parts-and-services/parts/partsasist/  Peru 
https://www.macktrucks.com.pe/parts-and-services/support/body-builders/wiring-diagrams/

Venezuela
https://www.macktrucks.com.ve/parts-and-services/support/body-builders/wiring-diagrams/

Haiti
https://www.macktrucks.ht/parts-and-services/support/body-builders/news-and-events/

Guatemala
https://www.macktrucks.gt/parts-and-services/support/body-builders/wiring-diagrams/
https://www.macktrucks.gt/about-mack/contact-us/

Honduras
https://www.macktrucks.hn/parts-and-services/support/body-builders/wiring-diagrams/

EMEA
https://www.macktrucksemea.com/trucks/events/

Trinidad & Tobago
https://tt.macktrucks.com/powertrain-and-suspensions/suspensions/mrIde/

@Kannan-CM

**Comment by silviulungu** [comment]
These links still not working:

Bolivia 
https://www.macktrucks.com.bo/parts-and-services/parts/partsasist/  

Haiti
https://www.macktrucks.ht/parts-and-services/support/body-builders/news-and-events/

Guatemala
https://www.macktrucks.gt/about-mack/contact-us/

Trinidad & Tobago
https://tt.macktrucks.com/powertrain-and-suspensions/suspensions/mrIde/

@Kannan-CM said that Peru must not have PartsAsist page, but is still up and running.
Peru must have PartsAsist page or not?
https://www.macktrucks.com.pe/parts-and-services/parts/partsasist/

**Comment by Kannan-CM** [comment]
@silviulungu ,
We don't have PartsAsist for Export markets.

For Trinidad & Tobago there is a typo in the URL it needs to be "mride".
Could you please let me know where did you find the URL, so I can update it.

**Comment by silviulungu** [comment]
Testing completed. Everything works accordingly!
